n = input('Digite algo:')
print('Seu tiṕo primitivo é:', type(n))
print('É numérico?', n.isnumeric())
print('Só tem espaços?', n.isspace())
print('É alfaumérico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('Só tem maiúscula?', n.isupper())
print('Só tem minúscula?', n.islower())
print('Está capitalizado?', n.istitle())